---
dependencies:
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http: ^1.1.0
environment:
  sdk: '>=3.0.6 <4.0.0'
flutter:
  assets:
    - assets/
  uses-material-design: true
name: beginners
publish_to: none
version: 1.0.0+1